# Generated by Django 4.1.3 on 2022-12-21 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('e_mail', models.EmailField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(help_text='viết Yêu Cầu Tư Vấn')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
